---
- name: Check if local fluentd certificate exists
  delegate_to: localhost
  run_once: true
  stat:
    path: "{{ local_fluentd_ca_cert_path }}"
  register: local_fluentd_ca_cert_path_exists

- name: Read fluentd certificate
  set_fact:
    fluentd_ca_cert: "{{ lookup('file', local_fluentd_ca_cert_path) }}"
  when: local_fluentd_ca_cert_path_exists.stat.exists

- name: Check if local fluentd elasticsearch CA certificate exists
  delegate_to: localhost
  run_once: true
  stat:
    path: "{{ local_fluentd_elasticsearch_ca_file_path }}"
  register: local_fluentd_elasticsearch_ca_file_path_exists
  when: fluentd_use_elasticsearch

- name: Read fluentd elasticsearch CA certificate
  set_fact:
    fluentd_elasticsearch_ca_file_contents: "{{ lookup('file', local_fluentd_elasticsearch_ca_file_path) }}"
  when:
  - fluentd_use_elasticsearch
  - local_fluentd_elasticsearch_ca_file_path_exists.stat.exists

- name: Check if local fluentd elasticsearch client certificate exists
  delegate_to: localhost
  run_once: true
  stat:
    path: "{{ local_fluentd_elasticsearch_client_cert_path }}"
  register: local_fluentd_elasticsearch_client_cert_path_exists
  when: fluentd_use_elasticsearch

- name: Read fluentd elasticsearch client certificate
  set_fact:
    fluentd_elasticsearch_client_cert_contents: "{{ lookup('file', local_fluentd_elasticsearch_client_cert_path) }}"
  when:
  - fluentd_use_elasticsearch
  - local_fluentd_elasticsearch_client_cert_path_exists.stat.exists

- name: Check if local fluentd elasticsearch client key exists
  delegate_to: localhost
  run_once: true
  stat:
    path: "{{ local_fluentd_elasticsearch_client_key_path }}"
  register: local_fluentd_elasticsearch_client_key_path_exists
  when: fluentd_use_elasticsearch

- name: Read fluentd elasticsearch client key
  set_fact:
    fluentd_elasticsearch_client_key_contents: "{{ lookup('file', local_fluentd_elasticsearch_client_key_path) }}"
  when:
  - fluentd_use_elasticsearch
  - local_fluentd_elasticsearch_client_key_path_exists.stat.exists
