---
- name: Set fluentd_elasticsearch_port fact
  set_fact:
    fluentd_elasticsearch_port: 9200
  when: not fluentd_elasticsearch_port is defined

- name: Remove secure_forward configuration
  file:
    state: absent
    path: '{{ fluentd_config_parts_dir }}/30-source-forward.conf'

- name: Install elasticsearch client configuration
  template:
    src: elasticsearch_output.conf
    dest: '{{ fluentd_config_parts_dir }}/30-elasticsearch-output.conf'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  notify: restart fluentd
